# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Boxotop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Boxotop
  pod 'SDWebImage/GIF'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'AlamofireImage'
  pod 'SwiftyStarRatingView'

  target 'BoxotopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoxotopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
